theme: jekyll-theme-minimal
title: Presentation slides
logo: /assets/img/vienna2.png
description: This is a repository for online slides and other materials used in conference presentations and other events.png
show_downloads: false
