theme: jekyll-theme-minimal
title: Web presentations
logo: https://github.com/CGMoreh/chrismoreh.com/blob/main/assets/media/profile2.jpg
description: This is a repository for presentation slides used at conferences and other events
